"use client";

import { useMemo, useState } from "react";

type Severity = "critical" | "high" | "medium" | "low" | "informational";
type Finding = {
  id: string; rule_id: string; title: string; severity: Severity; confidence: number; cvss: number; cwe: string; category: string;
  location: { file: string; line_start: number; line_end: number; snippet: string };
  summary: string; root_cause: string; attack_scenario: string; remediation: string; secure_example: string;
};
type ScanResult = {
  id: string; project: string; engine_version: string; completed_at: string; security_score: number; findings: Finding[];
  metrics: { rust_files: number; parsed_files: number; lines_of_code: number; functions: number; account_structs: number; pda_constraints: number; cpi_calls: number; dependencies: number };
  graph: { nodes: { id: string; label: string; kind: string }[]; edges: { source: string; target: string; relation: string }[]; level: string };
  limitations: string[];
};

const fallbackScan: ScanResult = {
  id: "scan_demo", project: "sentinel-vault", engine_version: "0.1.0", completed_at: new Date().toISOString(), security_score: 2,
  findings: [
    { id: "RBX001-demo", rule_id: "RBX001", title: "Authority is not typed as a signer", severity: "critical", confidence: 0.93, cvss: 9.1, cwe: "CWE-862", category: "Access control", location: { file: "programs/vault/src/lib.rs", line_start: 24, line_end: 24, snippet: "pub authority: AccountInfo<'info>," }, summary: "An authority account uses unchecked AccountInfo instead of Anchor's Signer type.", root_cause: "The account model does not require a transaction signature for the authority.", attack_scenario: "An attacker can substitute an arbitrary public key and invoke privileged state changes.", remediation: "Use Signer<'info> and bind it to the stored authority with a has_one or address constraint.", secure_example: "pub authority: Signer<'info>," },
    { id: "RBX003-demo", rule_id: "RBX003", title: "CPI target may be attacker-controlled", severity: "critical", confidence: 0.82, cvss: 9.0, cwe: "CWE-829", category: "Cross-program invocation", location: { file: "programs/vault/src/lib.rs", line_start: 16, line_end: 16, snippet: "invoke(&build_instruction(target.key()), ctx.remaining_accounts)?;" }, summary: "A raw CPI is assembled in a context that consumes remaining_accounts.", root_cause: "The invoked program identity is not evidently pinned to a trusted program ID.", attack_scenario: "A malicious program can receive the caller's forwarded signer privileges.", remediation: "Pin the target to a typed Program account or compare it with the expected program ID.", secure_example: "require_keys_eq!(target.key(), trusted_program::ID, ErrorCode::InvalidProgram);" },
    { id: "RBX002-demo", rule_id: "RBX002", title: "Unchecked account accepts substitution", severity: "high", confidence: 0.84, cvss: 8.1, cwe: "CWE-284", category: "Account validation", location: { file: "programs/vault/src/lib.rs", line_start: 25, line_end: 25, snippet: "pub external_state: UncheckedAccount<'info>," }, summary: "An UncheckedAccount is accepted without an evident declarative validation boundary.", root_cause: "Unchecked accounts bypass Anchor ownership and discriminator checks.", attack_scenario: "A crafted account can be substituted for trusted external state.", remediation: "Prefer a typed account or enforce owner, address, and data invariants.", secure_example: "#[account(owner = expected_program.key())]\npub external: UncheckedAccount<'info>," },
    { id: "RBX004-demo", rule_id: "RBX004", title: "Panic-prone execution path", severity: "medium", confidence: 0.96, cvss: 5.3, cwe: "CWE-248", category: "Reliability", location: { file: "programs/vault/src/lib.rs", line_start: 12, line_end: 12, snippet: "vault.balance = vault.balance.checked_sub(amount).unwrap();" }, summary: "A reachable unwrap can abort instruction execution instead of returning a program error.", root_cause: "Fallible arithmetic is converted with a panic.", attack_scenario: "A caller can force failed transactions with an oversized withdrawal.", remediation: "Return a typed Anchor error from checked arithmetic.", secure_example: "vault.balance = vault.balance.checked_sub(amount).ok_or(ErrorCode::InsufficientFunds)?;" },
    { id: "RBX005-demo", rule_id: "RBX005", title: "PDA constraint omits canonical bump", severity: "medium", confidence: 0.78, cvss: 6.0, cwe: "CWE-347", category: "PDA validation", location: { file: "programs/vault/src/lib.rs", line_start: 22, line_end: 22, snippet: "#[account(mut, seeds = [b\"vault\", authority.key.as_ref()])]" }, summary: "A PDA seed constraint does not visibly require Anchor's canonical bump.", root_cause: "Seed verification is incomplete without a canonical bump.", attack_scenario: "A non-canonical address can violate downstream assumptions.", remediation: "Add the bump constraint to the account declaration.", secure_example: "#[account(mut, seeds = [b\"vault\", authority.key().as_ref()], bump)]" },
  ],
  metrics: { rust_files: 1, parsed_files: 1, lines_of_code: 29, functions: 2, account_structs: 1, pda_constraints: 1, cpi_calls: 1, dependencies: 2 },
  graph: { level: "AST-derived project relationship graph (MVP)", nodes: [{ id: "vault", label: "vault/lib.rs", kind: "file" }, { id: "withdraw", label: "withdraw", kind: "instruction" }, { id: "accounts", label: "Withdraw", kind: "accounts" }, { id: "pda", label: "vault PDA", kind: "pda" }, { id: "cpi", label: "external CPI", kind: "cpi" }], edges: [{ source: "vault", target: "withdraw", relation: "contains" }, { source: "withdraw", target: "accounts", relation: "validates" }, { source: "accounts", target: "pda", relation: "derives" }, { source: "withdraw", target: "cpi", relation: "invokes" }] },
  limitations: ["CFG/DFG and symbolic execution are extension points, not implemented analyses in this MVP.", "Rules identify review candidates and do not replace a manual security audit.", "AI-assisted reasoning is disabled until a provider adapter is explicitly configured."],
};

const API = process.env.NEXT_PUBLIC_ROBOX_API ?? "http://127.0.0.1:8080";
const tabs = ["Overview", "Findings", "Program graph", "Reports"] as const;
type Tab = (typeof tabs)[number];

export default function Home() {
  const [scan, setScan] = useState<ScanResult>(fallbackScan);
  const [activeTab, setActiveTab] = useState<Tab>("Overview");
  const [selectedFinding, setSelectedFinding] = useState(0);
  const [sourceMode, setSourceMode] = useState<"files" | "github">("files");
  const [files, setFiles] = useState<File[]>([]);
  const [repo, setRepo] = useState("https://github.com/coral-xyz/anchor");
  const [isScanning, setIsScanning] = useState(false);
  const [notice, setNotice] = useState("Demo result loaded · connect the Rust API to scan new input");
  const counts = useMemo(() => ({ critical: scan.findings.filter((item) => item.severity === "critical").length, high: scan.findings.filter((item) => item.severity === "high").length, medium: scan.findings.filter((item) => item.severity === "medium").length, low: scan.findings.filter((item) => item.severity === "low").length }), [scan]);
  const finding = scan.findings[selectedFinding] ?? scan.findings[0];

  async function runDemo() {
    setIsScanning(true); setNotice("Rust engine · parsing AST and evaluating 6 rules");
    try { const response = await fetch(`${API}/api/v1/demo`); if (!response.ok) throw new Error("API unavailable"); setScan(await response.json()); setSelectedFinding(0); setNotice("Scan complete · result returned by the Rust engine"); }
    catch { await new Promise((resolve) => setTimeout(resolve, 700)); setScan(fallbackScan); setNotice("Local showcase mode · start the API for live project scans"); }
    finally { setIsScanning(false); }
  }

  async function runInputScan() {
    setIsScanning(true); setNotice("Preparing project input…");
    try {
      let source: object; let project = "uploaded-anchor-project";
      if (sourceMode === "files") {
        if (!files.length) { setNotice("Choose Rust or Cargo files before scanning"); setIsScanning(false); return; }
        const filePayload = await Promise.all(files.map(async (file) => ({ path: file.webkitRelativePath || file.name, content: await file.text() })));
        source = { type: "inline", files: filePayload }; project = files[0].webkitRelativePath.split("/")[0] || "uploaded-project";
      } else {
        if (!repo.startsWith("https://github.com/")) { setNotice("Enter a public https://github.com/owner/repository URL"); setIsScanning(false); return; }
        source = { type: "github", url: repo, branch: null }; project = repo.split("/").pop()?.replace(".git", "") || "github-project";
      }
      setNotice("Rust engine · scanning project source");
      const response = await fetch(`${API}/api/v1/scans`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ project, source }) });
      const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Scan failed");
      setScan(payload); setSelectedFinding(0); setActiveTab("Overview"); setNotice("Scan complete · findings are ready for review");
    } catch (error) { setNotice(error instanceof Error ? `${error.message} · verify that the Rust API is running` : "Scan failed"); }
    finally { setIsScanning(false); }
  }

  function downloadReport(format: "json" | "sarif" | "markdown") {
    let body = ""; let type = "text/plain"; let extension = "txt";
    if (format === "json") { body = JSON.stringify(scan, null, 2); type = "application/json"; extension = "json"; }
    if (format === "sarif") { body = JSON.stringify({ version: "2.1.0", runs: [{ tool: { driver: { name: "Robox", version: scan.engine_version } }, results: scan.findings.map((item) => ({ ruleId: item.rule_id, level: ["critical", "high"].includes(item.severity) ? "error" : "warning", message: { text: item.summary }, locations: [{ physicalLocation: { artifactLocation: { uri: item.location.file }, region: { startLine: item.location.line_start } } }] })) }] }, null, 2); type = "application/sarif+json"; extension = "sarif"; }
    if (format === "markdown") { body = `# Robox security audit: ${scan.project}\n\n**Security score:** ${scan.security_score}/100\n\n${scan.findings.map((item) => `## ${item.title}\n\n- Severity: ${item.severity}\n- Location: ${item.location.file}:${item.location.line_start}\n\n${item.summary}\n\n**Remediation:** ${item.remediation}`).join("\n\n")}`; type = "text/markdown"; extension = "md"; }
    const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(new Blob([body], { type })); anchor.download = `robox-${scan.project}.${extension}`; anchor.click(); URL.revokeObjectURL(anchor.href);
  }

  return <main className="app-shell">
    <aside className="sidebar">
      <button className="brand" onClick={() => setActiveTab("Overview")} aria-label="Robox home"><span className="brand-mark"><i /><i /><i /><i /></span><span>ROBOX</span></button>
      <nav className="side-nav" aria-label="Workspace navigation"><span className="nav-label">Workspace</span><button className={activeTab === "Overview" ? "active" : ""} onClick={() => setActiveTab("Overview")}><span>⌂</span> Overview</button><button className={activeTab === "Findings" ? "active" : ""} onClick={() => setActiveTab("Findings")}><span>◇</span> Findings <b>{scan.findings.length}</b></button><button className={activeTab === "Program graph" ? "active" : ""} onClick={() => setActiveTab("Program graph")}><span>⌘</span> Program graph</button><button className={activeTab === "Reports" ? "active" : ""} onClick={() => setActiveTab("Reports")}><span>▤</span> Reports</button><span className="nav-label second">Automation</span><button><span>↗</span> CI / CD</button><button><span>◫</span> Custom rules</button></nav>
      <div className="engine-card"><div className="engine-head"><span className="pulse-dot" /> Engine online</div><p>Rust core · v{scan.engine_version}</p><div className="mini-meter"><i /></div><small>6 / 6 rules loaded</small></div>
      <button className="profile"><span>MV</span><span><strong>Security workspace</strong><small>Local environment</small></span><b>•••</b></button>
    </aside>
    <section className="workspace">
      <header className="topbar"><div><span className="eyebrow">PROJECT</span><h1>{scan.project}<span>/</span><em>latest scan</em></h1></div><div className="top-actions"><span className="network"><i /> Localnet</span><button className="ghost-button" onClick={() => setActiveTab("Reports")}>Export report</button><button className="primary-button compact" onClick={runDemo} disabled={isScanning}>{isScanning ? "Scanning…" : "Run scan"}</button></div></header>
      <div className="content">
        <section className="scan-hero"><div className="hero-copy"><span className="section-kicker"><i /> SOLANA SECURITY INTELLIGENCE</span><h2>Audit at the speed<br />of <em>Rust.</em></h2><p>Import an Anchor program. Robox maps the surface, evaluates explainable security rules, and turns every risk into an actionable fix.</p><div className="trust-row"><span><b>AST</b> parsed</span><i /><span><b>100%</b> Rust engine</span><i /><span><b>SARIF</b> ready</span></div></div><div className="core-scene" aria-hidden="true"><div className="halo h1" /><div className="halo h2" /><div className="halo h3" /><div className="orb"><span>R</span><i /></div><div className="orbit o1"><i /></div><div className="orbit o2"><i /></div><span className="scene-label l1">AST</span><span className="scene-label l2">PDA</span><span className="scene-label l3">CPI</span></div><div className="import-card"><div className="mode-switch"><button className={sourceMode === "files" ? "active" : ""} onClick={() => setSourceMode("files")}>Local project</button><button className={sourceMode === "github" ? "active" : ""} onClick={() => setSourceMode("github")}>GitHub</button></div>{sourceMode === "files" ? <label className="drop-zone"><input type="file" accept=".rs,.toml" multiple onChange={(event) => setFiles(Array.from(event.target.files ?? []))} /><span className="upload-icon">＋</span><strong>{files.length ? `${files.length} project files selected` : "Drop Rust project files"}</strong><small>{files.length ? files.slice(0, 2).map((file) => file.name).join(" · ") : "Choose .rs and Cargo.toml files"}</small></label> : <div className="repo-input"><label htmlFor="repo">Repository URL</label><div><span>⌘</span><input id="repo" value={repo} onChange={(event) => setRepo(event.target.value)} /><button aria-label="Open repository">↗</button></div><small>Public GitHub repositories · default branch</small></div>}<button className="primary-button scan-button" onClick={runInputScan} disabled={isScanning}><span>{isScanning ? "◌" : "◆"}</span>{isScanning ? "Analyzing project…" : "Start security scan"}</button><div className="scan-notice"><i className={isScanning ? "loading" : ""} /><span>{notice}</span></div></div></section>
        <div className="tabs" role="tablist">{tabs.map((tab) => <button key={tab} role="tab" aria-selected={activeTab === tab} className={activeTab === tab ? "active" : ""} onClick={() => setActiveTab(tab)}>{tab}{tab === "Findings" && <span>{scan.findings.length}</span>}</button>)}</div>
        {activeTab === "Overview" && <Overview scan={scan} counts={counts} onFinding={() => setActiveTab("Findings")} onGraph={() => setActiveTab("Program graph")} />}
        {activeTab === "Findings" && <Findings scan={scan} selected={selectedFinding} onSelect={setSelectedFinding} finding={finding} />}
        {activeTab === "Program graph" && <ProgramGraph scan={scan} />}
        {activeTab === "Reports" && <Reports scan={scan} download={downloadReport} />}
      </div>
    </section>
  </main>;
}

function Overview({ scan, counts, onFinding, onGraph }: { scan: ScanResult; counts: Record<string, number>; onFinding: () => void; onGraph: () => void }) {
  return <div className="dashboard-grid"><section className="panel score-panel"><div className="panel-heading"><div><span className="eyebrow">SECURITY POSTURE</span><h3>Project risk score</h3></div><span className="live-pill"><i /> Complete</span></div><div className="score-content"><div className="score-ring" style={{ "--score": `${scan.security_score * 3.6}deg` } as React.CSSProperties}><div><strong>{scan.security_score}</strong><span>/100</span><small>{scan.security_score >= 80 ? "Healthy" : scan.security_score >= 50 ? "At risk" : "Critical risk"}</small></div></div><div className="risk-summary"><p>Deployment is <strong>{scan.security_score >= 70 ? "reviewable" : "not recommended"}</strong> until priority findings are resolved.</p><div className="severity-row"><span className="critical"><i />{counts.critical}<small>Critical</small></span><span className="high"><i />{counts.high}<small>High</small></span><span className="medium"><i />{counts.medium}<small>Medium</small></span><span className="low"><i />{counts.low}<small>Low</small></span></div><button onClick={onFinding}>Review priority findings <span>→</span></button></div></div></section><section className="panel metrics-panel"><div className="panel-heading"><div><span className="eyebrow">ANALYSIS COVERAGE</span><h3>Program surface</h3></div><span className="mono-tag">syn AST</span></div><div className="metric-grid"><Metric value={scan.metrics.rust_files} label="Rust files" trend="parsed" /><Metric value={scan.metrics.functions} label="Functions" trend="mapped" /><Metric value={scan.metrics.account_structs} label="Account groups" trend="validated" /><Metric value={scan.metrics.dependencies} label="Dependencies" trend="indexed" /></div><div className="coverage"><div><span>Parse coverage</span><strong>{Math.round((scan.metrics.parsed_files / Math.max(scan.metrics.rust_files, 1)) * 100)}%</strong></div><div className="coverage-bar"><i /></div><small>{scan.metrics.lines_of_code} source lines examined</small></div></section><section className="panel priority-panel"><div className="panel-heading"><div><span className="eyebrow">PRIORITY QUEUE</span><h3>Findings that need attention</h3></div><button onClick={onFinding}>View all →</button></div><div className="finding-preview">{scan.findings.slice(0, 3).map((item, index) => <button key={item.id} onClick={onFinding}><span className={`severity-icon ${item.severity}`}>{index + 1}</span><span><strong>{item.title}</strong><small>{item.location.file}:{item.location.line_start}</small></span><em className={item.severity}>{item.severity}</em><b>{Math.round(item.confidence * 100)}%</b></button>)}</div></section><section className="panel graph-preview"><div className="panel-heading"><div><span className="eyebrow">PROGRAM MODEL</span><h3>Instruction relationships</h3></div><button onClick={onGraph}>Expand ↗</button></div><MiniGraph /></section></div>;
}

function Metric({ value, label, trend }: { value: number; label: string; trend: string }) { return <div className="metric"><span>{label}</span><strong>{value.toString().padStart(2, "0")}</strong><small><i /> {trend}</small></div>; }

function Findings({ scan, selected, onSelect, finding }: { scan: ScanResult; selected: number; onSelect: (index: number) => void; finding?: Finding }) {
  return <div className="findings-layout"><section className="panel findings-list"><div className="panel-heading"><div><span className="eyebrow">{scan.findings.length} TOTAL FINDINGS</span><h3>Review queue</h3></div><button className="filter-button">Severity ↓</button></div>{scan.findings.map((item, index) => <button key={item.id} className={selected === index ? "selected" : ""} onClick={() => onSelect(index)}><span className={`severity-icon ${item.severity}`}>{item.severity.slice(0, 1).toUpperCase()}</span><span><strong>{item.title}</strong><small>{item.rule_id} · {item.location.file}:{item.location.line_start}</small></span><em className={item.severity}>{item.severity}</em><b>→</b></button>)}</section>{finding && <section className="panel finding-detail"><div className="detail-head"><div><span className={`severity-pill ${finding.severity}`}>{finding.severity}</span><span className="mono-tag">{finding.rule_id}</span></div><span>{Math.round(finding.confidence * 100)}% confidence · CVSS {finding.cvss}</span></div><h2>{finding.title}</h2><p>{finding.summary}</p><div className="code-location"><div><span>{finding.location.file}</span><b>Ln {finding.location.line_start}</b></div><pre><code><i>{finding.location.line_start}</i>{finding.location.snippet}</code></pre></div><div className="explanation-grid"><article><span className="eyebrow">ROOT CAUSE</span><p>{finding.root_cause}</p></article><article><span className="eyebrow">ATTACK PATH</span><p>{finding.attack_scenario}</p></article></div><div className="remediation"><span className="eyebrow">RECOMMENDED REMEDIATION</span><p>{finding.remediation}</p><pre><code>{finding.secure_example}</code></pre></div><div className="detail-footer"><span>{finding.cwe}</span><span>{finding.category}</span><button>Mark reviewed</button></div></section>}</div>;
}

function MiniGraph() { return <div className="mini-graph"><span className="graph-node program">Program</span><span className="graph-node instruction">withdraw</span><span className="graph-node account">Accounts</span><span className="graph-node pda">vault PDA</span><span className="graph-node cpi">CPI target</span><i className="line a" /><i className="line b" /><i className="line c" /><i className="line d" /></div>; }
function ProgramGraph({ scan }: { scan: ScanResult }) { return <section className="panel graph-panel"><div className="panel-heading"><div><span className="eyebrow">{scan.graph.level.toUpperCase()}</span><h3>Instruction and account map</h3></div><div className="graph-legend"><span><i className="instruction" />Instruction</span><span><i className="account" />Account</span><span><i className="risk" />Risk edge</span></div></div><div className="large-graph"><div className="grid-floor" /><MiniGraph /><div className="graph-note"><span>Model boundary</span><p>This graph is derived from parsed syntax and declarative Anchor accounts. Control-flow and data-flow edges are planned extension layers.</p></div></div><div className="graph-stats"><span><strong>{scan.graph.nodes.length}</strong> Nodes</span><span><strong>{scan.graph.edges.length}</strong> Relationships</span><span><strong>{scan.metrics.pda_constraints}</strong> PDA constraints</span><span><strong>{scan.metrics.cpi_calls}</strong> CPI calls</span></div></section>; }
function Reports({ scan, download }: { scan: ScanResult; download: (format: "json" | "sarif" | "markdown") => void }) { return <div className="reports-grid"><section className="panel report-summary"><span className="eyebrow">AUDIT ARTIFACT</span><h2>{scan.project}</h2><p>Generated from scan <code>{scan.id}</code> with Robox {scan.engine_version}.</p><div className="report-score"><span>Security score</span><strong>{scan.security_score}<small>/100</small></strong></div><div className="report-meta"><span><b>{scan.findings.length}</b> findings</span><span><b>{scan.metrics.rust_files}</b> files</span><span><b>{scan.metrics.lines_of_code}</b> LOC</span></div></section><section className="report-options"><ReportCard title="SARIF 2.1.0" description="GitHub Code Scanning compatible output with stable fingerprints and source regions." tag="CI READY" onClick={() => download("sarif")} /><ReportCard title="JSON" description="Complete machine-readable scan result for integrations, dashboards, and archival." tag="API" onClick={() => download("json")} /><ReportCard title="Markdown" description="Human-readable technical report for pull requests, auditors, and stakeholders." tag="REPORT" onClick={() => download("markdown")} /></section><section className="panel limitations"><span className="eyebrow">HONEST ANALYSIS BOUNDARY</span><h3>What this scan means</h3>{scan.limitations.map((item) => <p key={item}><i>✓</i>{item}</p>)}</section></div>; }
function ReportCard({ title, description, tag, onClick }: { title: string; description: string; tag: string; onClick: () => void }) { return <button className="panel report-card" onClick={onClick}><span className="document-icon"><i /><i /><i /></span><span><small>{tag}</small><strong>{title}</strong><p>{description}</p></span><b>↓</b></button>; }
